server:
  port: 8081

---

spring:
  profiles: development-ssl
server:
  port: 8081
  ssl.key-store: keystore\\6f3ddbf5-7e1a-4793-874a-d93e7cd8d6fa.pfx
  ssl.key-store-password: djswoopdidoo

---

spring:
  profiles: development
server:
  port: 8081